name: CI to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init and Apply
        run: |
          terraform init
          terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-west-2'

      - name: Terraform Output to JSON
        run: |
          terraform output -json > inventory.json
        id: terraform_output

      - name: Create Ansible Inventory
        run: |
          echo "[webserver]" > ansible_inventory
          echo "$(jq -r '.instance_ip.value' inventory.json) ansible_ssh_user=ubuntu ansible_ssh_private_key_file=${{ secrets.SSH_PRIVATE_KEY }}" >> ansible_inventory
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      
      
      - name: Configure EC2 with Ansible
        run: |
          ansible-playbook -i terraform-inventory ansible/playbook.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
